name: petdiary
description: "Social media application for paws!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'


flutter_icons: 
  android: true 
  ios: false 
  image_path: "assets/images/app_logo.png"

dependencies:
  flutter:
    sdk: flutter
  flutter_snake_navigationbar: ^0.6.1
  string_validator: ^1.0.2
  dio: ^5.4.0
  provider: ^6.1.2
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  sp_util: ^2.0.3
  image_picker: ^1.0.7
  easy_localization: ^3.0.5
  easy_localization_loader: ^2.0.1
  web_socket_channel: ^3.0.0
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  cloud_firestore: ^4.17.5
  firebase_core: ^2.32.0
  http: ^1.2.1
  image_cropper: ^7.0.1
  dotted_border: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/langs/
    - assets/images/app_logo.png
    - assets/images/onur.jpg
    - assets/images/asdasd.jpg

  fonts:
    - family: Handwrite
      fonts:
        - asset: assets/fonts/Indie_Flower/IndieFlower-Regular.ttf

    - family: Montserrat_Regular
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf

    - family: Montserrat_Bold
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf

    - family: Montserrat_ExtraBold
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraBold.ttf

    - family: Montserrat_Italic
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Italic.ttf

    - family: Montserrat_Light
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Light.ttf

    - family: Montserrat_LightItalic
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-LightItalic.ttf

    - family: Montserrat_Thin
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-ThinItalic.ttf

  uses-material-design: true
